# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'streaming' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for streaming

end

target 'streamingex' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for streamingex
  pod 'libdotEngine', :git => 'https://github.com/dotEngine/dotEngine-ios-sdk.git'
  pod 'GPUImage'
end

target 'streamingexUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for streamingexUI

end
